# Generated by Django 2.1.5 on 2020-04-26 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=64)),
                ('opposite', models.CharField(max_length=64)),
                ('info', models.CharField(max_length=64)),
                ('coins', models.IntegerField(default=0, verbose_name='Cчет')),
                ('wins', models.IntegerField(default=0, verbose_name='Победы')),
                ('total_games', models.IntegerField(default=0, verbose_name='Всего игр')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
