# Generated by Django 2.1.5 on 2020-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=0.5),
        ),
    ]
