# Generated by Django 2.1.5 on 2020-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200429_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=4.9),
        ),
    ]
