# Generated by Django 2.1.5 on 2020-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200429_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=-4.1),
        ),
    ]
