# Generated by Django 2.1.5 on 2020-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20200429_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameitem',
            old_name='choice',
            new_name='selected',
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=-0.7),
        ),
    ]
