# Generated by Django 2.1.5 on 2020-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200429_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='last_rate',
            field=models.IntegerField(default=0, verbose_name='Последний приход'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=-0.9),
        ),
    ]
