# Generated by Django 2.1.5 on 2020-05-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200430_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameitem',
            name='enemy_wins',
            field=models.IntegerField(default=0, verbose_name='Победы противника'),
        ),
        migrations.AddField(
            model_name='gameitem',
            name='my_wins',
            field=models.IntegerField(default=0, verbose_name='Мои обеды'),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='win_rate_change',
            field=models.FloatField(default=-1.3),
        ),
    ]
